### ISSUE TITLE
Your plugin proposal on catalog

### ISSUE THREAD

**Issue by orthagh** [yild/gdprowner#2]
Hello.

I received the submission for this plugin on the plugins catalog (and your xml).

Just one thing to fix : please add a proper logo url to your xml.
After that, i'll accept your plugin.

Regards

**Comment by yild** [comment]
it's done

**Comment by yild** [comment]
@orthagh
please  ignory my submision to glpi plugins catalog, there are some modifications needed before publish - I will resend it in some time
Thanks

**Comment by orthagh** [comment]
Ok i remove the entry, just resend it when you think it's ready
